databases:
  - name: ed-u

services:
  - type: web
    name: ed-u
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ed-u
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false