default: &default
  adapter: postgresql
  encoding: unicode
  #comment out host and credentials to host locally
  # host: db
  # username: postgres
  # password: password
  pool: 5

development:
  <<: *default
  database: ed-u_development

test:
  <<: *default
  database: ed-u_test

production:
  <<: *default
  database: ed-u_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  url: <%= ENV['DB_URL'] %>
